spring:
  application:
    name: Clinic

  datasource:
    username: usuario
    password: usuario
    url: jdbc:mysql://10.2.244.119:3306/commander_reliquary
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
