spring:
  application:
    name: Clinic

  datasource:
    username: root
    password: Root@1234
    url: jdbc:mysql://localhost:3306/clinica
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
